# Generated by Django 3.2.9 on 2021-11-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageuser',
            name='there_is_pd',
            field=models.BooleanField(default=False, verbose_name='Есть ли личные данные'),
        ),
    ]
