# Generated by Django 3.2.9 on 2021-11-20 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_auto_20211119_1448'),
        ('tgbot', '0003_auto_20211119_1509'),
    ]

    operations = [
    ]
