# Generated by Django 3.2.9 on 2021-11-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_merge_0003_auto_20211119_1448_0003_auto_20211119_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='store_duration_type',
            field=models.CharField(choices=[('0', 'неделя'), ('1', 'месяц')], default='0', max_length=1, verbose_name='Единица длительности хранения'),
        ),
    ]
